sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDNva4NJqkMVA3VQyZX
    access-key-secret: s1xiS4qdQojW3zWv8ppBiTySZX96WM
    bucket-name: sky-take-out-moyoo0
  redis:
    host: localhost
    port: 6379
    database: 1
  wechat:
    appid: wx185465100144ac8b
    secret: eb1b63d48ff87fec08dd6f1a44bf1e9c


